using Shellfox.Native;
using Xunit;

namespace Shellfox.Native.Tests;
public class SessionWindowsTests {
 static BoundWindow Binding(string? session=null,string? generation=null)=>new(new("windows-terminal","shellfox-"+(session??=Guid.NewGuid().ToString()),"123",new(1,"100"),session,"SHELLFOX:"+session+":","native-title"),generation??Guid.NewGuid().ToString());
 static Registration Registration(BoundWindow b,int pid=10,string time="200")=>new(b.Target.SessionId,Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),new(pid,time),@"C:\Program Files\PowerShell\7\pwsh.exe",@"C:\test",Wire.Now());
 [Fact] public void OldWindowLossCannotInvalidateReplacement(){var s=new SessionWindows();var old=Binding();s.Remember(old);Assert.True(s.MarkLost(old));var next=Binding(old.Target.SessionId);s.Remember(next);Assert.False(s.MarkLost(old));Assert.True(s.IsCurrent(next));}
 [Fact] public void SameAuthenticatedShellTransfersOneMemberAndKeepsTabIdentity(){var s=new SessionWindows();var a=Binding();var b=Binding();s.Remember(a);s.Remember(b);var connection=Guid.NewGuid().ToString();var first=s.Adopt(Registration(a),connection,a);var moved=s.Adopt(Registration(b),connection,b);Assert.Equal(first.Member,moved.Previous);Assert.Equal(first.Member.Registration.TabId,moved.Member.Registration.TabId);Assert.Empty(s.Members(a.Target.SessionId));Assert.Single(s.Members(b.Target.SessionId));}
 [Fact] public void PidReuseIsNotAMove(){var s=new SessionWindows();var a=Binding();s.Remember(a);s.Adopt(Registration(a),Guid.NewGuid().ToString(),a);s.Adopt(Registration(a,time:"201"),Guid.NewGuid().ToString(),a);Assert.Equal(2,s.Members(a.Target.SessionId).Length);}
 [Fact] public void ChangedConnectionCannotTransferExistingRoot(){var s=new SessionWindows();var a=Binding();s.Remember(a);s.Adopt(Registration(a),Guid.NewGuid().ToString(),a);Assert.Throws<NativeError>(()=>s.Adopt(Registration(a),Guid.NewGuid().ToString(),a));}
 [Fact] public void OldSourceWatchIsRejectedAfterConfirmedTransfer(){var s=new SessionWindows();var a=Binding();var b=Binding();s.Remember(a);s.Remember(b);var first=s.Adopt(Registration(a),null,a).Member;var watch=new Watch([new(first.Registration.SessionId,first.Registration.TabId,first.Registration)],[]);Assert.True(s.Allows(watch));s.Adopt(Registration(b),null,b);Assert.False(s.Allows(watch));}
 [Fact] public void StaleCloseCannotRemoveNewMembership(){var s=new SessionWindows();var a=Binding();var b=Binding();s.Remember(a);s.Remember(b);var first=s.Adopt(Registration(a),null,a).Member;var current=s.Adopt(Registration(b),null,b).Member;Assert.False(s.Remove(first));Assert.True(s.Remove(current));}
 [Fact] public void ConnectionIdentityCannotProduceTwoMembersViaNestedShell(){var s=new SessionWindows();var a=Binding();s.Remember(a);var connection=Guid.NewGuid().ToString();s.Adopt(Registration(a),connection,a);Assert.Throws<NativeError>(()=>s.Adopt(Registration(a,pid:11),connection,a));}
 [Fact] public void RestoreCannotOverwriteLiveReplacement(){var s=new SessionWindows();var old=Binding();var next=Binding(old.Target.SessionId);s.Remember(next);Assert.Throws<NativeError>(()=>s.Restore(new([old],[])));Assert.True(s.IsCurrent(next));}
 [Fact] public void RestoredShellCannotHaveTwoOwners(){var s=new SessionWindows();var a=Binding();var r=Registration(a);var member=new MemberRegistration(r,null,a);Assert.Throws<NativeError>(()=>s.Restore(new([a],[member,member])));}
 [Fact] public void ReplacementReservationIsUniquePerPreviousGeneration(){var dir=Path.Combine(Directory.GetCurrentDirectory(),"tmp","replacement-unit",Guid.NewGuid().ToString());var p=new WindowLaunchPolicy(dir);var old=Binding();var r=new Launch(old.Target.SessionId,Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),@"C:\test","pwsh",@"C:\pwsh.exe","unused","unused",null);p.ReserveReplacement(r,old);Assert.Throws<NativeError>(()=>new WindowLaunchPolicy(dir).ReserveReplacement(r with {OperationId=Guid.NewGuid().ToString()},old));Assert.Equal(new[]{"--window","new"},WindowLaunchPolicy.SelectorArguments());}
}
